### ISSUE TITLE
Version Problem - Issues

### ISSUE THREAD

**Issue by jeffersonswartz** [sumanMalware/projectRepo#1]
1. Make sure all the names of the interfaces follow UpperCamelCase.
Link for naming convention reference [https://google.github.io/styleguide/tsguide.html](https://google.github.io/styleguide/tsguide.html)

---
2. We can have another interface for the bugs instead of having it as any.
https://github.com/sumanMalware/projectRepo/blob/1a84feb3b2cbb4da313f31bf9a19f4ed8594e56b/versionData.ts#L7
For Example: 
```typescript
interface Bug {
    id: number;
    bugDescription: string;
}
```

---

3. Since update type is a generic key for all versions we can have it as enum
 https://github.com/sumanMalware/projectRepo/blob/1a84feb3b2cbb4da313f31bf9a19f4ed8594e56b/versionData.ts#L36
For Example:
```typescript
enum UpdateType {
    MAJOR,
    MINOR,
}

// Use it as
{
    ...
    updateType: UpdateType.MAJOR;
    ...
}
```

---
4. Instead of using `any` for the function parameters try to put the exact type we need for the param to be 
https://github.com/sumanMalware/projectRepo/blob/1a84feb3b2cbb4da313f31bf9a19f4ed8594e56b/versionData.ts#L104

---
5. Same as the above comment, Make sure you put the exact type the variable will be instead of `any`.
https://github.com/sumanMalware/projectRepo/blob/1a84feb3b2cbb4da313f31bf9a19f4ed8594e56b/versionData.ts#L106

---

6. Every different action we do needs to be a function and also the bug id is hard coded here instead it should be passed to a param of a function.

The `bugs` object inside the data is an array so we should be iterating over it to find the exact bug. Referencing the `[0]` element is not the right solution.

https://github.com/sumanMalware/projectRepo/blob/1a84feb3b2cbb4da313f31bf9a19f4ed8594e56b/versionData.ts#L118-L123

---

7.  This should also be made as a function. Also this function can be simplified with the use of Array.Sort.
For Reference : [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort)
https://github.com/sumanMalware/projectRepo/blob/1a84feb3b2cbb4da313f31bf9a19f4ed8594e56b/versionData.ts#L135-L164

---

8. Instead of calling the same method twice we can call it once and store it in a variable and use it in multiple places. Thus we can reduce the number of operations

https://github.com/sumanMalware/projectRepo/blob/1a84feb3b2cbb4da313f31bf9a19f4ed8594e56b/versionData.ts#L177

---

### Summary
---

- Use of any should be reduced, Try to add the exact type for the variable
- Every function should be made with the idea of being reusable, so all the hard-coded text should be passed as params.
- Good job on following the indentation and spacing, also try to follow the naming conventions for variables, interfaces, etc.

**Comment by sumanNayak29** [comment]
Thank you for reviewing my code and provide your valuable feedback. I will go through with your instruction.

Regards
-Suman Nayak
